/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.21
 * Generated at: 2011-11-23 01:56:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<title>Anna's Big Math</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"resources/css/style.css\" type=\"text/css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body onload=\"setNums();\">\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    \r\n");
      out.write("    var numCorrect = 0;\r\n");
      out.write("</script>\r\n");
      out.write("<script src=\"//ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"random.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"validate.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"jquery.shuffleLetters.js\"></script>\r\n");
      out.write("<form action=\"\" onsubmit=\"return validate()\">\r\n");
      out.write("<!--  \r\n");
      out.write("<div id=\"countSection\">\r\n");
      out.write("\t<p id=\"countTitle\">Count</p>\r\n");
      out.write("\t<p id=\"count\"></p>\r\n");
      out.write("\t<p id=\"countHex\"></p>\r\n");
      out.write("\t<p id=\"countBinary\"></p>\r\n");
      out.write("\t<p id=\"countSquares\"></p>\r\n");
      out.write("\t<p id=\"countFib\"></p>\r\n");
      out.write("</div>\r\n");
      out.write(" -->\r\n");
      out.write("<div id=\"equation\">\r\n");
      out.write("\t<span id=\"operands\">\r\n");
      out.write("\t\t<span id=\"first\"></span>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t<span id=\"bottom_line\">\r\n");
      out.write("\t\t\t<span id=\"operator\"></span>\r\n");
      out.write("\t\t\t<span id=\"second\"></span>\r\n");
      out.write("\t\t</span>\r\n");
      out.write("\t\t<br/>\r\n");
      out.write("\t\t<input id=\"math_answer\" type=\"text\"/>\r\n");
      out.write("\t\t\r\n");
      out.write("\t</span>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"conclusion\">\r\n");
      out.write("\t<span id=\"correct\"></span>\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
